apiVersion: v1
kind: Pod
metadata:
  name: grafana
spec:
  containers:
    - name: grafana
      image: grafana/grafana:latest
      ports:
        - containerPort: 3000
      env:
        - name: GF_SERVER_HTTP_PORT
          value: "4000"
        - name: GF_SERVER_HTTP_ADDR
          value: "0.0.0.0"
      volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
  volumes:
    - name: grafana-data
      emptyDir: {}
