apiVersion: v1
kind: Pod
metadata:
  name: prometheus
spec:
  containers:
    - name: prometheus
      image: prom/prometheus:latest
      ports:
        - containerPort: 9090
      volumeMounts:
        - mountPath: /prometheus
          name: prometheus-data
      args:
        - "--config.file=/etc/prometheus/prometheus.yml"
  volumes:
    - name: prometheus-data
      emptyDir: {}
